### ISSUE TITLE
this.parentContainer.hideLayer is not a function

### ISSUE THREAD

**Issue by hoticer** [vue-leaflet/Vue2Leaflet#506]
this.parentContainer.hideLayer is not a function

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions
- Leaflet: v1.6.0
- Vue: v4.0.5
- Vue2Leaflet: v2.4.1

**Comment by hoticer** [comment]
![Snipaste_2019-12-27_15-34-59](https://user-images.githubusercontent.com/10001817/71507159-792b4e80-28be-11ea-8051-c2cb8c2bbcea.png)

**Comment by hoticer** [comment]
I think it's due to this commit - https://github.com/vue-leaflet/Vue2Leaflet/commit/17367fa705d76a6053a7a2a9270aa5f1bb67e2ac

**Comment by DonNicoJs** [comment]
@hoticer Thanks for the issue to facilitate my investigation could you tell me what components are you using and mounted in what order (in other words your component tree )

**Comment by hoticer** [comment]
@DonNicoJs 
my component tree is like this.
<l-map>
  <l-layer-group ref="gridImageLayerGroup" :visible="gridImageLayerGroup.visible">
        <l-layer-group ref="gridImageLayer" :visible="gridImageLayer.visible"/>
        <l-layer-group ref="gridValueLayer" :visible="gridValueLayer.visible"/>
      </l-layer-group>
</l-map>

so the final l-layer-group's parent is still  l-layer-group rather than l-map. so .hideLayer function is not found.

**Comment by DonNicoJs** [comment]
@hoticer Thanks! now I can tackle this.

**Comment by DonNicoJs** [comment]
@hoticer Happy new year :) I've released 2.4.2 with a small fix for this, the naive approach is to call `removeLayer` if `hideLayer` is not defined, I believe this should cover most of the use cases, could you confirm?

**Comment by hoticer** [comment]
@DonNicoJs Happy new year!!!  I test it's ok! Vue2Leaflet is very good!!!

**Comment by hoticer** [comment]
@DonNicoJs Something is wrong. 
```
<l-map>
  <l-layer-group ref="gridImageLayerGroup" :visible="gridImageLayerGroup.visible">
        <l-layer-group ref="gridImageLayer" :visible="gridImageLayer.visible"/>
        <l-layer-group ref="gridValueLayer" :visible="gridValueLayer.visible"/>
      </l-layer-group>
</l-map>
```
When I set gridImageLayerGroup.visible = false, the gridImageLayer and gridValueLayer are still show. I think hideLayer only hide gridImageLayerGroup itself . But children aren't be hidden.
